### ISSUE TITLE
Add separate block type for table header

### ISSUE THREAD

**Issue by punitjajodia** [punitjajodia/nirmaan#2]
Right now both 'td' and 'th' have same block type.

**Comment by punitjajodia** [comment]
Checking how the Slate.js render shows the table header, perhaps they assume that the first `tr`'s children are `th`.

**Comment by parewa-ranjit** [comment]
While importing HTML, table headers are not working.
![image](https://user-images.githubusercontent.com/9676299/58609349-fa8a1680-82c6-11e9-8a20-98b855b3d1fc.png)

Also, you cannot create table headers. It looks as if the first row is column header due to CSS but it's not.
![image](https://user-images.githubusercontent.com/9676299/58609453-52c11880-82c7-11e9-8e34-bf5922fa7bfd.png)
